// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BucketClient is an autogenerated mock type for the BucketClient type
type BucketClient struct {
	mock.Mock
}

// DownloadVideo provides a mock function with given fields: key
func (_m *BucketClient) DownloadVideo(key string) (string, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for DownloadVideo")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadFrame provides a mock function with given fields: localPath, userID
func (_m *BucketClient) UploadFrame(localPath string, userID string) (string, error) {
	ret := _m.Called(localPath, userID)

	if len(ret) == 0 {
		panic("no return value specified for UploadFrame")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(localPath, userID)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(localPath, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(localPath, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBucketClient creates a new instance of BucketClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBucketClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *BucketClient {
	mock := &BucketClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
