// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FrameProcessor is an autogenerated mock type for the FrameProcessor type
type FrameProcessor struct {
	mock.Mock
}

// ExtractFrames provides a mock function with given fields: videoPath
func (_m *FrameProcessor) ExtractFrames(videoPath string) ([]string, error) {
	ret := _m.Called(videoPath)

	if len(ret) == 0 {
		panic("no return value specified for ExtractFrames")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(videoPath)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(videoPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(videoPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFrameProcessor creates a new instance of FrameProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFrameProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *FrameProcessor {
	mock := &FrameProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
