// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FrameRepository is an autogenerated mock type for the FrameRepository type
type FrameRepository struct {
	mock.Mock
}

// SaveFrames provides a mock function with given fields: userID, videoKey, urls
func (_m *FrameRepository) SaveFrames(userID string, videoKey string, urls []string) error {
	ret := _m.Called(userID, videoKey, urls)

	if len(ret) == 0 {
		panic("no return value specified for SaveFrames")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, []string) error); ok {
		r0 = rf(userID, videoKey, urls)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewFrameRepository creates a new instance of FrameRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFrameRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FrameRepository {
	mock := &FrameRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
